
### Begin yaml necessary for Book's Website ###
project:
  type: website
  output-dir: docs

website:
  title: "Data Analysis 101 -- Exploratory Data Analysis using R programming."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01OverviewOfR.qmd
      - 02RPackages.qmd
      - 03InbuiltRFunctions.qmd
### End yaml necessary for Book's Website ###
### Begin yaml necessary for Book's PDF ###
#project:
#  type: book
### End yaml necessary for Book's PDF ###

book:
  title: "Data Analysis 101 -- Exploratory Data Analysis using R programming."
  author: "Sameer Mathur, Aryeman Gupta Mathur"
  date: "4 July 2023"
  page-footer:
    left: |
      Data Analysis 101 -- Exploratory Data Analysis using R programming by Sameer Mathur, Aryeman G. Mathur
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: bookcovertemplate.png
  favicon: bookcovertemplate.png
  chapters:
    - index.qmd
    - 01OverviewOfR.qmd
    - 02RPackages.qmd
#    - 03InbuiltRFunctions.qmd
#    - 04DataStructures.qmd
#    - 05ReadingData.qmd
#    - 06SummarzingCategoricalData.qmd
#    - 07SummarizingContinuousData.qmd
#    - 08SummarizingContinuousData.qmd
#    - 09SummarizingContinuousData.qmd
#    - references.qmd
#bibliography: references.bib

format:
  html:
    theme:
     dark: cosmo
    toc: true # may need to comment this out to revert this back to the book
    fig-width: 8
    fig-height: 4
    code-fold: false
  pdf:
    documentclass: scrreport
    header-includes: |
      \titlehead{
        \begin{center}
          \includegraphics[width=5in]{bookcovertemplate.png}
        \end{center}
      }

editor: visual

