
### BEGIN yaml FOR BOOK'S WEBSITE ###
project:
  type: website
  output-dir: docs

website:
  title: "Data Analysis 101 -- Exploratory Data Analysis using R programming."
#  body-header: | 
#    by Sameer Mathur and Aryeman Gupta Mathur
  margin-header: |
    ![](bookcovertemplate.png)  
  page-footer:
    background: "blue"
    center: 
      - text: "Sameer Mathur"
        href: https://www.qatar.cmu.edu/directory/sameer-mathur/
      - text: "Aryeman Gupta Mathur"
        href: https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&ouid=100224206438187222136&rtpof=true&sd=true
  navbar:
    background: "blue"
    pinned: false
    search: false
    right: 
      - icon: globe
        href: https://www.qatar.cmu.edu/directory/sameer-mathur/
        text: "Sameer Mathur"
        target: "_blank"
      - icon: globe
        href: https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&ouid=100224206438187222136&rtpof=true&sd=true
        text: "Aryeman Gupta Mathur"
        target: "_blank"
      - icon: github
        href: https://github.com/AryemanGuptaMathur/Data_Analytics_101
        text: "Book's Github"
        target: "_blank"
#    left:
#      - href: index.qmd
#        text: H
#      - 01OverviewOfR.qmd
  sidebar:
#    logo: "images/openscapes_hex.png"
#    background: "black"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    footer: "Website by Aryeman"
    contents:
      - href: index.qmd
        text: Home
      - 01OverviewOfR.qmd
      - 02RPackages.qmd
      - 03InbuiltRFunctions.qmd
#      - section: quarto-workflows/index.qmd
#        contents: 
#          - quarto-workflows/browser.md
#          - quarto-workflows/rstudio.qmd
#          - quarto-workflows/jupyter.md 
#      - learning-more.qmd
#      - href: transition-from-rmarkdown.qmd
#        text: Transition from Rmd
### END yaml FOR BOOK'S WEBSITE ###


### Begin yaml necessary for Book's PDF ###
#project:
#  type: book
### End yaml necessary for Book's PDF ###




book:
  title: "Data Analysis 101 -- Exploratory Data Analysis using R programming."
  author: "Sameer Mathur, Aryeman Gupta Mathur"
  date: "4 July 2023"
  page-footer:
    left: |
      Data Analysis 101 -- Exploratory Data Analysis using R programming by Sameer Mathur, Aryeman G. Mathur
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: bookcovertemplate.png
  favicon: bookcovertemplate.png
  chapters:
    - index.qmd
    - 01OverviewOfR.qmd
    - 02RPackages.qmd
#    - 03InbuiltRFunctions.qmd
#    - 04DataStructures.qmd
#    - 05ReadingData.qmd
#    - 06SummarzingCategoricalData.qmd
#    - 07SummarizingContinuousData.qmd
#    - 08SummarizingContinuousData.qmd
#    - 09SummarizingContinuousData.qmd
#    - references.qmd
#bibliography: references.bib

format:
  html:
    theme: 
     dark: cosmo
    toc: true # may need to comment this out to revert this back to the book
    fig-width: 8
    fig-height: 4
    code-fold: false
  pdf:
    documentclass: scrreport
    header-includes: |
      \titlehead{
        \begin{center}
          \includegraphics[width=5in]{bookcovertemplate.png}
        \end{center}
      }

editor: visual

